### ISSUE TITLE
Roadmap to Paper

### ISSUE THREAD

**Issue by aelligp** [JuliaGeodynamics/GeophysicalModelGenerator.jl#56]
- [x] update/test Tutorial
- [x] update Docs
- [x] add Contribution.md, Authors.md, Contributing (license)
- [x] add Codecov
- [x] Change function names to lowercase

**Comment by mthielma** [comment]
Tutorials that don't work
- [ ] GPS tutorial

**Comment by boriskaus** [comment]
Finished
